### ISSUE TITLE
Failed to install newest version(1.1.1) by using CocoaPods.

### ISSUE THREAD

**Issue by r-kojima** [mercari/BottomHalfModal#3]
When I tried to install `BottomHalfModal` on my project by using CocoaPods without specifying version, installed version was `1.0.0`.
I want to use `BottomHalfModal` of version `1.1.1`.
Please update installable version on Cocoapods.

(This is my first Issue on Github, Sorry if my English is incorrect.)

**Comment by masamichiueta** [comment]
@r-kojima Thanks for your contribution! I have updated cocoa pods version, and now 1.1.1 is available.
